# GripperInfo.msg
## Contains data about the gripper detected by the system

### The type of gripper, will probably be RG2 or RG6
string gripper_type

### The ip address of the gripper
string ip
### The port of the gripper
string port

### The maximum width the gripper can open in milimetres
int32 max_width
### The maximum force the gripper can exert, in centinewtons (10ths of a newton)
int32 max_force